/*
* Each new term in the Fibonacci sequence is generated by adding the previous two terms.
* By starting with 1 and 2, the first 10 terms will be:
* 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
* By considering the terms in the Fibonacci sequence whose values do not exceed four million,
* find the sum of the even-valued terms.
*
* output should be 4613732
*/

#include <iostream>
#include <algorithm>

using namespace std;

int main()
{
	int total = 0, curr = 1, next = 2;

	while (curr <= 4000000)
	{
		if (curr % 2 == 0)
		{
			total += curr;
		}
		//XOR swap only works on int types, fun to show off, don't use in practice
		//curr = curr ^ next, next = curr ^ next, curr = curr ^ next;
		//algorithm library has built in swap, no need to reimplement the wheel
		swap(curr, next);
		next = next + curr;
	}

	cout << total;
}
